### ISSUE TITLE
Visual Identity

### ISSUE THREAD

**Issue by zeropaper** [METAKRONISMS/METAKRONISMS.github.io#13]
- [x] Logo
- [x] Graphic Chart
- [x] Favicon
- [x] Ambiant background (general background)*
- [x] Episode theme images
   - [x] Episode theme
   - [x] Perspective 1 theme
   - [x] Perspective 2 theme
   - [x] Perspective 3 theme

**Comment by AdrianeMorard** [comment]
@zeropaper 
Files: https://drive.google.com/drive/folders/1eWvjozfoX592xXuRUzqs1ABaCfhZ_Fz7

- Font license: KRSNA: Ok up to 10 workspaces and webfont license included. Libre Franklin is a google font.
- Ambiant Background: Very simple shiny dots - maybe possible to do it in JS instead of using an image? There's also a deep purple sort of cloudy nebula. Also JS? Animation wise, could we make something very discreet? Such as the purple nebula slightly following the movement of the mouse for example, and/or the starts varying in size to give an impression of movement...?
- The episode theme image is coming!

**Comment by zeropaper** [comment]
@AdrianeMorard Cool!

* just so… could you check that the favicon is still OK for you in the following resolutions (I suspect that it will be fine from 256 and up but I fear it might become "unreadable" in lower resolutions):
  * 1024x1024
  * 512x512
  * 256x256
  * 128x128
  * 64x64
  * 32x32
  * 16x16
* I think I could be able to make something for the background, in case you feel like digging a more precise direction, NASA has an amazing CC collection of images… (that's where I took the moon surface picture used so far, https://www.metakronisms.art/static/PIA23236_hires-c34dd086391781c682f4412eb505a920.jpg) https://www.nasa.gov/multimedia/imagegallery/index.html

**Comment by AdrianeMorard** [comment]
@zeropaper Yeah thank you! I made a simpler one, in the same dropbox folder. It should be fine!
